title: Lucas Peitton
baseURL: https://lucas-peitton-data.netlify.app/
theme: hugo-resume
languageCode: en-us
PygmentsCodeFences: yes
PygmentsCodeFencesGuessSyntax: yes
PygmentsStyle: monokai
enableGitInfo: no
params:
  address: Rosario, Argentina
  email: lucasph97@gmail.com
  favicon: /favicon.ico
  firstName: Lucas
  # google:
  #   analytics:
  #     trackerID: XX-123446-01
  handles:
    - link: https://www.linkedin.com/in/lucas-peitton/
      name: LinkedIn
    - link: https://github.com/lucasph97/
      name: GitHub
  lastName: Peitton
  # phone: 1-555-555-1234
<<<<<<< HEAD
  profileImage: img/foto_120623.jpg
=======
  profileImage: img/foto_120623.jpeg
>>>>>>> ca7ed179ec71f29519b272dd873e6a81d5808371
  sections:
    - skills
    - publications
    - creations
    - contributions
    - experience
    - education
    - blog
  showContact: yes
  showQr: no
outputs:
  home:
    - HTML
    - JSON
taxonomies:
  tag: tags
